module I18n exposing (I18n, Language(..), decoder, greeting, init, languageFromString, languageSwitchInfo, languageToString, languages, load, order, order1, order10, order11, order12, order13, order14, order15, order16, order17, order18, order19, order2, order20, order3, order4, order5, order6, order7, order8, order9)

{-| This file was generated by elm-i18n.


-}

import Http
import Json.Decode
import Json.Decode.Pipeline
import Placeholder.DoubleCurly


type alias I18nInstance =
    { greeting_ : String -> String
    , languageSwitchInfo_ : String -> String
    , order_ : String -> String -> String
    , order1_ : String -> String -> String
    , order10_ : String -> String -> String
    , order11_ : String -> String -> String
    , order12_ : String -> String -> String
    , order13_ : String -> String -> String
    , order14_ : String -> String -> String
    , order15_ : String -> String -> String
    , order16_ : String -> String -> String
    , order17_ : String -> String -> String
    , order18_ : String -> String -> String
    , order19_ : String -> String -> String
    , order2_ : String -> String -> String
    , order20_ : String -> String -> String
    , order3_ : String -> String -> String
    , order4_ : String -> String -> String
    , order5_ : String -> String -> String
    , order6_ : String -> String -> String
    , order7_ : String -> String -> String
    , order8_ : String -> String -> String
    , order9_ : String -> String -> String
    }


type I18n
    = Loaded I18nInstance
    | NotLoaded


init : I18n
init =
    NotLoaded


type Language
    = De
    | En


languages : List Language
languages =
    [ De, En ]


languageToString : Language -> String
languageToString lang_ =
    case lang_ of
        De ->
            "de"

        En ->
            "en"


languageFromString : String -> Maybe Language
languageFromString lang_ =
    case lang_ of
        "de" ->
            Just De

        "en" ->
            Just En

        _ ->
            Nothing


fallbackValue_ : String
fallbackValue_ =
    "..."


decoder : Json.Decode.Decoder I18n
decoder =
    Json.Decode.succeed I18nInstance
        |> Json.Decode.Pipeline.required "0" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph1)
        |> Json.Decode.Pipeline.required "1" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph1)
        |> Json.Decode.Pipeline.required "2" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "3" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "4" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "5" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "6" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "7" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "8" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "9" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "10" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "11" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "12" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "13" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "14" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "15" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "16" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "17" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "18" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "19" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "20" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "21" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.Pipeline.required "22" (stringParserToDecoder Placeholder.DoubleCurly.parsePlaceholderAlph2)
        |> Json.Decode.map Loaded


load : { language : Language, path : String, onLoad : Result Http.Error I18n -> msg } -> Cmd msg
load opts_ =
    Http.get
        { expect = Http.expectJson opts_.onLoad decoder
        , url = opts_.path ++ "/messages." ++ languageToString opts_.language ++ ".json"
        }


stringParserToDecoder : (String -> Result String a) -> Json.Decode.Decoder a
stringParserToDecoder f =
    Json.Decode.string
        |> Json.Decode.andThen
            (\str ->
                case f str of
                    Ok ok ->
                        Json.Decode.succeed ok

                    Err err ->
                        Json.Decode.fail err
            )


greeting : I18n -> String -> String
greeting i18n_ name_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.greeting_ name_

        NotLoaded ->
            fallbackValue_


languageSwitchInfo : I18n -> String -> String
languageSwitchInfo i18n_ currentLanguage_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.languageSwitchInfo_ currentLanguage_

        NotLoaded ->
            fallbackValue_


order : I18n -> { a | language : String, name : String } -> String
order i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order1 : I18n -> { a | language : String, name : String } -> String
order1 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order1_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order10 : I18n -> { a | language : String, name : String } -> String
order10 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order10_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order11 : I18n -> { a | language : String, name : String } -> String
order11 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order11_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order12 : I18n -> { a | language : String, name : String } -> String
order12 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order12_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order13 : I18n -> { a | language : String, name : String } -> String
order13 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order13_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order14 : I18n -> { a | language : String, name : String } -> String
order14 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order14_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order15 : I18n -> { a | language : String, name : String } -> String
order15 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order15_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order16 : I18n -> { a | language : String, name : String } -> String
order16 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order16_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order17 : I18n -> { a | language : String, name : String } -> String
order17 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order17_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order18 : I18n -> { a | language : String, name : String } -> String
order18 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order18_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order19 : I18n -> { a | language : String, name : String } -> String
order19 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order19_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order2 : I18n -> { a | language : String, name : String } -> String
order2 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order2_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order20 : I18n -> { a | language : String, name : String } -> String
order20 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order20_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order3 : I18n -> { a | language : String, name : String } -> String
order3 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order3_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order4 : I18n -> { a | language : String, name : String } -> String
order4 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order4_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order5 : I18n -> { a | language : String, name : String } -> String
order5 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order5_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order6 : I18n -> { a | language : String, name : String } -> String
order6 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order6_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order7 : I18n -> { a | language : String, name : String } -> String
order7 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order7_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order8 : I18n -> { a | language : String, name : String } -> String
order8 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order8_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_


order9 : I18n -> { a | language : String, name : String } -> String
order9 i18n_ placeholders_ =
    case i18n_ of
        Loaded instance_ ->
            instance_.order9_ placeholders_.language placeholders_.name

        NotLoaded ->
            fallbackValue_
