module I18n exposing (I18n, de, en)

{-| This file was generated by elm-i18n version 2.1.4.


-}


type alias I18n =
    { demoKey : String
    , greeting : String -> String
    , languageSwitchInfo : String -> String
    , order : { language : String, name : String } -> String
    , static : String
    }


{-| `I18n` instance containing all values for the language En


-}
en : I18n
en =
    { demoKey = "demoValue"
    , greeting = \name_ -> "Hello " ++ name_
    , languageSwitchInfo =
        \currentLanguage_ -> "You may switch languages from " ++ currentLanguage_ ++ " to another one here."
    , order =
        \data_ ->
            "The order of the named placeholder keys stays consistent even when switching languages! Language: "
                ++ data_.language
                ++ ", Name: "
                ++ data_.name
                ++ "."
    , static = "Static text"
    }


{-| `I18n` instance containing all values for the language De


-}
de : I18n
de =
    { demoKey = "demoWert"
    , greeting = \name_ -> "Hallo " ++ name_
    , languageSwitchInfo =
        \currentLanguage_ -> "Du kannst hier deine Sprache von " ++ currentLanguage_ ++ " zu einer anderen ändern."
    , order =
        \data_ ->
            "Die Reihenfolge der benannten Platzhalter bleibt konsistent auch wenn die Sprachen sich ändern! Name: "
                ++ data_.name
                ++ ", Sprache: "
                ++ data_.language
    , static = "Statischer Text"
    }
