module I18n exposing (I18n, de, en, greeting, languageSwitchInfo, order, static)

{-| This file was generated by elm-i18n version 1.2.0.


-}


type alias I18n =
    { greeting_ : String -> String
    , languageSwitchInfo_ : String -> String
    , order_ : String -> String -> String
    , static_ : String
    }


greeting : I18n -> String -> String
greeting i18n_ name_ =
    i18n_.greeting_ name_


languageSwitchInfo : I18n -> String -> String
languageSwitchInfo i18n_ currentLanguage_ =
    i18n_.languageSwitchInfo_ currentLanguage_


order : I18n -> { a | language : String, name : String } -> String
order i18n_ placeholders_ =
    i18n_.order_ placeholders_.language placeholders_.name


static : I18n -> String
static i18n_ =
    i18n_.static_


{-| `I18n` instance containing all values for the language De


-}
de : I18n
de =
    { greeting_ = \name_ -> "Hallo " ++ name_
    , languageSwitchInfo_ =
        \currentLanguage_ -> "Du kannst hier deine Sprache von " ++ currentLanguage_ ++ " zu einer anderen ändern."
    , order_ =
        \language_ name_ ->
            "Die Reihenfolge der benannten Platzhalter bleibt konsistent auch wenn die Sprachen sich ändern! Name: "
                ++ name_
                ++ ", Sprache: "
                ++ language_
    , static_ = "Statischer Text"
    }


{-| `I18n` instance containing all values for the language En


-}
en : I18n
en =
    { greeting_ = \name_ -> "Hello " ++ name_
    , languageSwitchInfo_ =
        \currentLanguage_ -> "You may switch languages from " ++ currentLanguage_ ++ " to another one here."
    , order_ =
        \language_ name_ ->
            "The order of the named placeholder keys stays consistent even when switching languages! Language: "
                ++ language_
                ++ ", Name: "
                ++ name_
                ++ "."
    , static_ = "Static text"
    }
